networks:
  thesis_net:
    external: true
services:
 nginx:
   image: vulhub/nginx:1.4.2
   volumes:
    - ./nginx.conf:/usr/local/nginx/conf/nginx.conf
    - ./index.php:/usr/local/nginx/html/index.php
    - ./init.sh:/init.sh
   cap_add:
    - NET_ADMIN    
   entrypoint: ["sh", "/init.sh"]
   networks:
    thesis_net:
        ipv4_address: 172.20.0.30
   ports:
    - "8080:80"
 php:
   image: vulhub/php:5.6-fpm
   command: 
    - bash
    - -c
    - "mkdir -p /var/www/html/uploadfiles && chown -R www-data:www-data /var/www/html/uploadfiles && php-fpm"
   volumes:
    - ./index.php:/var/www/html/index.php
    - ./www.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
   networks:
    thesis_net:
        ipv4_address: 172.20.0.11
    

