version: '2'
networks:
  thesis_net:
    external: true
services:
 web:
   image: vulhub/bash:4.3.0-with-httpd
   ports:
    - "8080:80"
   volumes:
    - ./safe.cgi:/var/www/html/safe.cgi
    - ./victim.cgi:/var/www/html/victim.cgi
    - ./init.sh:/init.sh
   entrypoint: ["sh", "init.sh"]
   cap_add:
    - "NET_ADMIN"
   networks:
    - thesis_net
