version: '3'
networks:
  thesis_net:
    external: true
services:
 web:
   image: vulhub/geoserver:2.23.2
   ports:
    - "7777:8080"
    - "5005:5005"
   volumes:
    - ./init.sh:/init.sh
   cap_add:
    - NET_ADMIN    
   entrypoint: ["sh", "/init.sh"]
   networks:
    thesis_net:
        ipv4_address: 172.20.0.8
