version: '2'
networks:
  thesis_net:
    external: true
services:
 activemq:
   image: vulhub/activemq:5.11.1
   ports:
    - "61616:61616"
    - "8161:8161"
   cap_add:
      - NET_ADMIN
   volumes:
      - ./init.sh:/init.sh
   entrypoint: ["sh", "/init.sh"]
   mem_limit: 512m
   memswap_limit: 1g
   ulimits:
     nofile:
       soft: 65536
       hard: 65536
   networks:
    - thesis_net
